---
title: "Explore New Site Data"
author: "Simran Makwana & Alba Gutierrez"
date: "6/27/2023"
output: html_document
---
# Load Packages
```{r}
library(dplyr)
library(lubridate)
```

# Read the file from the site and extract the labs 
```{r}
new_site_data <- read.csv("../local_ref/texasChildren/misc_observations.csv")

lab_data <- new_site_data %>%
  dplyr::filter( is.na(Medication.Specification))

med_data <- new_site_data %>%
  dplyr::filter( !is.na(Medication.Specification))
```

# For the labs identify how many of the loincs we have from the eCRF are present
```{r}
eCRF2loinc <- read.csv('../data/eCRF_to_LOINC_forReview2.0.csv')

present <- eCRF2loinc %>%
  dplyr::filter( LOINC.CODE %in% lab_data$Concept.code )
```



```{r}
# create the summary for each concept_cd
subset <- new_site_data %>%
  dplyr::mutate( date = sapply(strsplit(Date, "[ ]"), '[', 1), 
                 date = as.Date( date, format =  "%m/%d/%y") ) %>%
  dplyr::filter( Concept.code %in% present$LOINC.CODE, 
                 !is.na( `Numeric.Value`)) %>%
  dplyr::rename( patient_num = `MUSIC.Patient.ID`, 
                 concept_cd = `Concept.code`, 
                 units_cd = `Lab.Units`, 
                 nval_num = `Numeric.Value`) %>%
  dplyr::select( patient_num, concept_cd, nval_num, units_cd, date )


check_summary <- subset %>%
  dplyr::group_by(concept_cd, units_cd) %>%
  dplyr::summarise( min_val = min(nval_num, na.rm = TRUE), 
                    max_val = max(nval_num, na.rm = TRUE), 
                    min_date = min( ymd( date) ), 
                    max_date = max( ymd( date ) ), 
                    distinct_patients = length(unique(patient_num)), 
                    distinct_observations = length(patient_num)) %>%
  dplyr::select( concept_cd, min_date, max_date, 
                 distinct_patients, distinct_observations, 
                 min_val, max_val, units_cd)
```
