---
title: "test redcap data download and upload"
author: "Simran Makwana"
date: "10/8/2021"
output: html_document
---

```{r}
existing_data <- read.csv('~/Downloads/MUSIC_DATA_2021-10-08_1011.csv')

datadict <- read.csv('common_ref/MUSIC_DataDictionary_V3_4Dec20_final version_clean_0.csv')

library(tidyverse)

```

```{r}
# demographics: obtain list of demographics variables
dem <- datadict %>%
  filter(Form.Name == 'demographics') %>%
  pull(Variable...Field.Name)

# filter existing data to demographics, record id, redcap_event_name, redcap_repeat_instrument, redcap_repeat_instance
existing_demographics <- existing_data[,colnames(existing_data) %in% c(dem, 'record_id', 'redcap_event_name', 'redcap_repeat_instrument', 'redcap_repeat_instance')] %>%
  filter(redcap_event_name == 'day_1_arm_1') %>%
  filter(dob != '')

```


```{r}
# format zipcodes to 5 digits
format_zip <- function(code) {ifelse(length(as.character(code) < 5), paste0(0, code), paste0(code))}
existing_demographics <- existing_demographics %>% mutate(zipcodeus = sapply(zipcodeus, format_zip))

```

```{r}
# write existing demographics data to file
write.csv(existing_demographics, 'demographics/local_ref/manually_entered_BCH_demographics.csv', row.names = FALSE, na = '')

```




